apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mdhp

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-deploy.yaml
  - postgres-svc.yaml
  - zookeeper-deploy.yaml
  - zookeeper-svc.yaml
  - kafka-deploy.yaml
  - kafka-svc.yaml
  - kafdrop-deploy.yaml
  - kafdrop-svc.yaml
  - metadata-deploy.yaml
  - metadata-svc.yaml
  - gateway-deploy.yaml
  - gateway-svc.yaml
