apiVersion: v1
kind: Service
metadata:
  name: mdhp-metadata-service
spec:
  selector:
    app: mdhp-metadata-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
